# Generated by Django 4.2.18 on 2025-02-10 16:10

import Gestion.validadores
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0002_alter_empleados_options_empleados_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
                'db_table': 'Departamentos',
            },
        ),
        migrations.AlterField(
            model_name='empleados',
            name='cargo',
            field=models.CharField(choices=[('Gerente', 'Gerente'), ('Vendedor', 'Vendedor'), ('Cajero', 'Cajero'), ('Supervisor', 'Supervisor'), ('Administrador', 'Administrador'), ('Asistente', 'Asistente'), ('Seguridad', 'Seguridad')], max_length=50),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='cedula',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.MaxLengthValidator(10), Gestion.validadores.validacion_numeros]),
        ),
        migrations.CreateModel(
            name='Salario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_pago', models.DateField()),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salarios', to='Gestion.empleados')),
            ],
            options={
                'verbose_name': 'Salario',
                'verbose_name_plural': 'Salarios',
                'db_table': 'Salarios',
            },
        ),
        migrations.CreateModel(
            name='Beneficio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('seguro', 'Seguro Médico'), ('bono', 'Bono de Rendimiento'), ('vacaciones', 'Días de Vacaciones'), ('otro', 'Otro')], max_length=50)),
                ('descripcion', models.TextField()),
                ('monto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fecha_asignacion', models.DateField()),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficios', to='Gestion.empleados')),
            ],
            options={
                'verbose_name': 'Beneficio',
                'verbose_name_plural': 'Beneficios',
                'db_table': 'Beneficios',
            },
        ),
    ]
