# Generated by Django 4.2.18 on 2025-02-10 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0003_departamento_alter_empleados_cargo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='departamento',
            name='empleados',
            field=models.ManyToManyField(related_name='departamentos', to='Gestion.empleados'),
        ),
    ]
